services:
  # The frontend web service running your Spring Boot via Docker
  - type: web
    name: training-dashboard
    env: docker
    rootDir: training
    region: singapore
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: DB_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: DB_HOST
        fromDatabase:
          name: training-postgres
          property: host
      - key: DB_PORT
        fromDatabase:
          name: training-postgres
          property: port
      - key: DB_NAME
        fromDatabase:
          name: training-postgres
          property: database
      - key: DB_USER
        fromDatabase:
          name: training-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: training-postgres
          property: password

databases:
  # The connected PostgreSQL Database that comes free on Render
  - name: training-postgres
    plan: free
    region: singapore
