# database connection
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/training_db}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root123}

# jpa settings
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.MySQLDialect}

# server port
server.port=${PORT:8080}